#ifndef CONFIG_H
#define CONFIG_H

#define DEFAULT_BORDER_SIZE 4
#define DEFAULT_BORDER_COLOR 0x420dab
#define DEFAULT_SELECTION_OUTPUT_FORMAT "%wx%h+%x+%y"
#define DEFAULT_POINT_OUTPUT_FORMAT "%x %y"

#endif
